name: sdrconnect
services:
  rsp-dx:
    container_name: rsp-dx
    image: dgadams/sdrconnect
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/bus/usb
    command:
      - "/sdr/SDRconnect"
      - "--server"
      - "--port=50000"
      - "--centerfrequency=95500000"
      - "--antenna=1"
      - "--hwser=2103083B44"

 
