name: sdrconnect-headless
services:
  sdrconnect-headless:
    container_name: sdrconnect-headless
    image: dgadams/sdrconnect-headless
    restart: unless-stopped
    init: true
    devices:
      - /dev/bus/usb
    command:
      - "--websocket_port=5454"
    network_mode: host
