name: sdrconnect-headless
services:
  sdrconnect-headless:
    container_name: sdrconnect-headless
    image: dgadams/sdrconnect
    restart: unless-stopped
    init: true
    network_mode: host
    devices:
      - /dev/bus/usb
    command: 
      - "/sdr/SDRconnect_headless"
      - "--websocket_port=5454"
